In [71]:
import pandas as pd
import numpy as np

In [72]:
data_honda = pd.read_csv('../DATOS/Honda.csv')

In [73]:
#LIMPIEZA DATOS
data_honda=data_honda.drop(columns=["Date","Open","High","Low","Adj Close","Volume"])

In [74]:
#PREPARAR DATOS
numero_periodos=5
def determinar_estado(cambio):
    if cambio > -0.40 and cambio < 0.40 :
        return 'Estable'
    elif cambio < 0:
        return 'Bajo'
    else:
        return 'Subio'

data_honda['Cambio'] = data_honda['Close'].diff()
data_honda['EstadoNuevo'] = data_honda['Cambio'].apply(determinar_estado)

data_honda_dividido= np.array_split(data_honda,numero_periodos)


c:\Users\Carlos Abdala\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)


In [75]:
# FRECUENCIA OBSERVADA
frecuencia_obs_1 = pd.crosstab(data_honda_dividido[0]['EstadoNuevo'].shift(), data_honda_dividido[0]['EstadoNuevo'], normalize=False)
print("FRECUENCIA OBSERVADA - PERIODO 1 \n", frecuencia_obs_1, "\n")
frecuencia_obs_2 = pd.crosstab(data_honda_dividido[1]['EstadoNuevo'].shift(), data_honda_dividido[1]['EstadoNuevo'], normalize=False)
print("FRECUENCIA OBSERVADA - PERIODO 2 \n", frecuencia_obs_2, "\n")
frecuencia_obs_3 = pd.crosstab(data_honda_dividido[2]['EstadoNuevo'].shift(), data_honda_dividido[2]['EstadoNuevo'], normalize=False)
print("FRECUENCIA OBSERVADA - PERIODO 3 \n", frecuencia_obs_3, "\n")
frecuencia_obs_4 = pd.crosstab(data_honda_dividido[3]['EstadoNuevo'].shift(), data_honda_dividido[3]['EstadoNuevo'], normalize=False)
print("FRECUENCIA OBSERVADA - PERIODO 4 \n", frecuencia_obs_4, "\n")
frecuencia_obs_5 = pd.crosstab(data_honda_dividido[4]['EstadoNuevo'].shift(), data_honda_dividido[4]['EstadoNuevo'], normalize=False)
print("FRECUENCIA OBSERVADA - PERIODO 5 \n", frecuencia_obs_5, "\n")

print(np.sum(frecuencia_obs_1))
frecuencias_observadas = [frecuencia_obs_1, frecuencia_obs_2, frecuencia_obs_3, frecuencia_obs_4, frecuencia_obs_5]

FRECUENCIA OBSERVADA - PERIODO 1 
 EstadoNuevo  Bajo  Estable  Subio
EstadoNuevo                      
Bajo            8        5      6
Estable         8        8      3
Subio           3        7      4 

FRECUENCIA OBSERVADA - PERIODO 2 
 EstadoNuevo  Bajo  Estable  Subio
EstadoNuevo                      
Bajo            4        5     10
Estable         6        4      4
Subio           9        4      5 

FRECUENCIA OBSERVADA - PERIODO 3 
 EstadoNuevo  Bajo  Estable  Subio
EstadoNuevo                      
Bajo            3        6      5
Estable         5       11      7
Subio           5        6      3 

FRECUENCIA OBSERVADA - PERIODO 4 
 EstadoNuevo  Bajo  Estable  Subio
EstadoNuevo                      
Bajo            5        5      3
Estable         5       11      8
Subio           3        8      3 

FRECUENCIA OBSERVADA - PERIODO 5 
 EstadoNuevo  Bajo  Estable  Subio
EstadoNuevo                      
Bajo            6        1      7
Estable         1        5      6
S

c:\Users\Carlos Abdala\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


In [76]:
#PROBABILIDAD OBSERVADA
probabilidad_obs_1= pd.crosstab(data_honda_dividido[0]['EstadoNuevo'].shift(), data_honda_dividido[0]['EstadoNuevo'], normalize=True)
print("PROBABILIDAD OBSERVADA - PERIODO 1 \n",probabilidad_obs_1,"\n")
probabilidad_obs_2= pd.crosstab(data_honda_dividido[1]['EstadoNuevo'].shift(), data_honda_dividido[1]['EstadoNuevo'], normalize=True)
print("PROBABILIDAD OBSERVADA - PERIODO 2 \n",probabilidad_obs_2,"\n")
probabilidad_obs_3= pd.crosstab(data_honda_dividido[2]['EstadoNuevo'].shift(), data_honda_dividido[2]['EstadoNuevo'], normalize=True)
print("PROBABILIDAD OBSERVADA - PERIODO 3 \n",probabilidad_obs_3,"\n")
probabilidad_obs_4= pd.crosstab(data_honda_dividido[3]['EstadoNuevo'].shift(), data_honda_dividido[3]['EstadoNuevo'], normalize=True)
print("PROBABILIDAD OBSERVADA - PERIODO 4 \n",probabilidad_obs_4,"\n")
probabilidad_obs_5= pd.crosstab(data_honda_dividido[4]['EstadoNuevo'].shift(), data_honda_dividido[4]['EstadoNuevo'], normalize=True)
print("PROBABILIDAD OBSERVADA - PERIODO 5 \n",probabilidad_obs_5,)

probabilidades_observadas=[probabilidad_obs_1,probabilidad_obs_2,probabilidad_obs_3,probabilidad_obs_4,probabilidad_obs_5]

PROBABILIDAD OBSERVADA - PERIODO 1 
 EstadoNuevo      Bajo   Estable     Subio
EstadoNuevo                              
Bajo         0.153846  0.096154  0.115385
Estable      0.153846  0.153846  0.057692
Subio        0.057692  0.134615  0.076923 

PROBABILIDAD OBSERVADA - PERIODO 2 
 EstadoNuevo      Bajo   Estable     Subio
EstadoNuevo                              
Bajo         0.078431  0.098039  0.196078
Estable      0.117647  0.078431  0.078431
Subio        0.176471  0.078431  0.098039 

PROBABILIDAD OBSERVADA - PERIODO 3 
 EstadoNuevo      Bajo   Estable     Subio
EstadoNuevo                              
Bajo         0.058824  0.117647  0.098039
Estable      0.098039  0.215686  0.137255
Subio        0.098039  0.117647  0.058824 

PROBABILIDAD OBSERVADA - PERIODO 4 
 EstadoNuevo      Bajo   Estable     Subio
EstadoNuevo                              
Bajo         0.098039  0.098039  0.058824
Estable      0.098039  0.215686  0.156863
Subio        0.058824  0.156863  0.058824 

PROB

In [77]:
probabilidad_esp= pd.crosstab(data_honda['EstadoNuevo'].shift(), data_honda['EstadoNuevo'], normalize=True)
print("PROBABILIDAD ESPERADA\n",probabilidad_esp,)

PROBABILIDAD ESPERADA
 EstadoNuevo      Bajo   Estable     Subio
EstadoNuevo                              
Bajo         0.100000  0.084615  0.119231
Estable      0.096154  0.153846  0.107692
Subio        0.107692  0.119231  0.111538


In [83]:
#CHI CUADRADO
nivelConfianza = 0.95
alpha = 1 - nivelConfianza
valorCritico = 9.488
observado_chi=0

for indice_periodo in range(numero_periodos):
    observado_chi+=np.sum(np.sum(frecuencias_observadas[indice_periodo]).values*(probabilidades_observadas[indice_periodo].values-probabilidad_esp.values)**2/probabilidad_esp.values)
    print(np.sum(frecuencias_observadas[indice_periodo]).values,"\n")
    print(probabilidades_observadas[indice_periodo].values)
    print(probabilidad_esp.values)

grados_libertad = ((probabilidad_esp.shape[1]-1)*(probabilidad_esp.shape[0]-1))
print("Chi Observado= ",observado_chi)
print("Grados de Libertad= ",grados_libertad)


[19 20 13] 

[[0.15384615 0.09615385 0.11538462]
 [0.15384615 0.15384615 0.05769231]
 [0.05769231 0.13461538 0.07692308]]
[[0.1        0.08461538 0.11923077]
 [0.09615385 0.15384615 0.10769231]
 [0.10769231 0.11923077 0.11153846]]
[19 13 19] 

[[0.07843137 0.09803922 0.19607843]
 [0.11764706 0.07843137 0.07843137]
 [0.17647059 0.07843137 0.09803922]]
[[0.1        0.08461538 0.11923077]
 [0.09615385 0.15384615 0.10769231]
 [0.10769231 0.11923077 0.11153846]]
[13 23 15] 

[[0.05882353 0.11764706 0.09803922]
 [0.09803922 0.21568627 0.1372549 ]
 [0.09803922 0.11764706 0.05882353]]
[[0.1        0.08461538 0.11923077]
 [0.09615385 0.15384615 0.10769231]
 [0.10769231 0.11923077 0.11153846]]
[13 24 14] 

[[0.09803922 0.09803922 0.05882353]
 [0.09803922 0.21568627 0.15686275]
 [0.05882353 0.15686275 0.05882353]]
[[0.1        0.08461538 0.11923077]
 [0.09615385 0.15384615 0.10769231]
 [0.10769231 0.11923077 0.11153846]]
[14 12 25] 

[[0.11764706 0.01960784 0.1372549 ]
 [0.01960784 0.09803922 0.1