In [50]:
import pandas as pd
import numpy as np

In [51]:
data_honda = pd.read_csv('../DATOS/Honda.csv')

In [52]:
#LIMPIEZA DATOS
data_honda=data_honda.drop(columns=["Date","Open","High","Low","Adj Close","Volume"])

In [60]:
#PREPARAR DATOS
numero_periodos=5
def determinar_estado(cambio):
    if cambio > -0.20 and cambio < 0.20 :
        return 'Estable'
    elif cambio < 0:
        return 'Bajo'
    else:
        return 'Subio'

data_honda['Cambio'] = data_honda['Close'].diff()
data_honda['EstadoNuevo'] = data_honda['Cambio'].apply(determinar_estado)

data_honda_dividido= np.array_split(data_honda,numero_periodos)


c:\Users\Carlos Abdala\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)


In [61]:
# FRECUENCIA OBSERVADA
frecuencia_obs_1 = pd.crosstab(data_honda_dividido[0]['EstadoNuevo'].shift(), data_honda_dividido[0]['EstadoNuevo'], normalize=False)
print("FRECUENCIA OBSERVADA - PERIODO 1 \n", frecuencia_obs_1, "\n")
frecuencia_obs_2 = pd.crosstab(data_honda_dividido[1]['EstadoNuevo'].shift(), data_honda_dividido[1]['EstadoNuevo'], normalize=False)
print("FRECUENCIA OBSERVADA - PERIODO 2 \n", frecuencia_obs_2, "\n")
frecuencia_obs_3 = pd.crosstab(data_honda_dividido[2]['EstadoNuevo'].shift(), data_honda_dividido[2]['EstadoNuevo'], normalize=False)
print("FRECUENCIA OBSERVADA - PERIODO 3 \n", frecuencia_obs_3, "\n")
frecuencia_obs_4 = pd.crosstab(data_honda_dividido[3]['EstadoNuevo'].shift(), data_honda_dividido[3]['EstadoNuevo'], normalize=False)
print("FRECUENCIA OBSERVADA - PERIODO 4 \n", frecuencia_obs_4, "\n")
frecuencia_obs_5 = pd.crosstab(data_honda_dividido[4]['EstadoNuevo'].shift(), data_honda_dividido[4]['EstadoNuevo'], normalize=False)
print("FRECUENCIA OBSERVADA - PERIODO 5 \n", frecuencia_obs_5, "\n")

print(np.sum(frecuencia_obs_1))
frecuencias_observadas = [frecuencia_obs_1, frecuencia_obs_2, frecuencia_obs_3, frecuencia_obs_4, frecuencia_obs_5]

FRECUENCIA OBSERVADA - PERIODO 1 
 EstadoNuevo  Bajo  Estable  Subio
EstadoNuevo                      
Bajo           11        4      8
Estable         6        1      2
Subio           6        4     10 

FRECUENCIA OBSERVADA - PERIODO 2 
 EstadoNuevo  Bajo  Estable  Subio
EstadoNuevo                      
Bajo            7        2     12
Estable         2        0      3
Subio          12        3     10 

FRECUENCIA OBSERVADA - PERIODO 3 
 EstadoNuevo  Bajo  Estable  Subio
EstadoNuevo                      
Bajo           10        3     10
Estable         5        2      1
Subio           7        3     10 

FRECUENCIA OBSERVADA - PERIODO 4 
 EstadoNuevo  Bajo  Estable  Subio
EstadoNuevo                      
Bajo           12        5      6
Estable         4        2      5
Subio           7        4      6 

FRECUENCIA OBSERVADA - PERIODO 5 
 EstadoNuevo  Bajo  Estable  Subio
EstadoNuevo                      
Bajo            6        2      7
Estable         1        3      4
S

c:\Users\Carlos Abdala\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


In [62]:
#PROBABILIDAD OBSERVADA
probabilidad_obs_1= pd.crosstab(data_honda_dividido[0]['EstadoNuevo'].shift(), data_honda_dividido[0]['EstadoNuevo'], normalize=True)
print("PROBABILIDAD OBSERVADA - PERIODO 1 \n",probabilidad_obs_1,"\n")
probabilidad_obs_2= pd.crosstab(data_honda_dividido[1]['EstadoNuevo'].shift(), data_honda_dividido[1]['EstadoNuevo'], normalize=True)
print("PROBABILIDAD OBSERVADA - PERIODO 2 \n",probabilidad_obs_2,"\n")
probabilidad_obs_3= pd.crosstab(data_honda_dividido[2]['EstadoNuevo'].shift(), data_honda_dividido[2]['EstadoNuevo'], normalize=True)
print("PROBABILIDAD OBSERVADA - PERIODO 3 \n",probabilidad_obs_3,"\n")
probabilidad_obs_4= pd.crosstab(data_honda_dividido[3]['EstadoNuevo'].shift(), data_honda_dividido[3]['EstadoNuevo'], normalize=True)
print("PROBABILIDAD OBSERVADA - PERIODO 4 \n",probabilidad_obs_4,"\n")
probabilidad_obs_5= pd.crosstab(data_honda_dividido[4]['EstadoNuevo'].shift(), data_honda_dividido[4]['EstadoNuevo'], normalize=True)
print("PROBABILIDAD OBSERVADA - PERIODO 5 \n",probabilidad_obs_5,)

probabilidades_observadas=[probabilidad_obs_1,probabilidad_obs_2,probabilidad_obs_3,probabilidad_obs_4,probabilidad_obs_5]

PROBABILIDAD OBSERVADA - PERIODO 1 
 EstadoNuevo      Bajo   Estable     Subio
EstadoNuevo                              
Bajo         0.211538  0.076923  0.153846
Estable      0.115385  0.019231  0.038462
Subio        0.115385  0.076923  0.192308 

PROBABILIDAD OBSERVADA - PERIODO 2 
 EstadoNuevo      Bajo   Estable     Subio
EstadoNuevo                              
Bajo         0.137255  0.039216  0.235294
Estable      0.039216  0.000000  0.058824
Subio        0.235294  0.058824  0.196078 

PROBABILIDAD OBSERVADA - PERIODO 3 
 EstadoNuevo      Bajo   Estable     Subio
EstadoNuevo                              
Bajo         0.196078  0.058824  0.196078
Estable      0.098039  0.039216  0.019608
Subio        0.137255  0.058824  0.196078 

PROBABILIDAD OBSERVADA - PERIODO 4 
 EstadoNuevo      Bajo   Estable     Subio
EstadoNuevo                              
Bajo         0.235294  0.098039  0.117647
Estable      0.078431  0.039216  0.098039
Subio        0.137255  0.078431  0.117647 

PROB

In [63]:
probabilidad_esp= pd.crosstab(data_honda['EstadoNuevo'].shift(), data_honda['EstadoNuevo'], normalize=True)
print("PROBABILIDAD ESPERADA\n",probabilidad_esp,)

PROBABILIDAD ESPERADA
 EstadoNuevo      Bajo   Estable     Subio
EstadoNuevo                              
Bajo         0.176923  0.061538  0.165385
Estable      0.069231  0.030769  0.057692
Subio        0.157692  0.065385  0.215385


In [70]:
#CHI CUADRADO
nivelConfianza = 0.95
alpha = 1 - nivelConfianza
valorCritico = 9.488
observado_chi=0

for indice_periodo in range(numero_periodos):
    observado_chi+=np.sum(np.sum(frecuencias_observadas[indice_periodo]).values*(probabilidades_observadas[indice_periodo].values-probabilidad_esp.values)**2/probabilidad_esp.values)
    print(np.sum(frecuencias_observadas[indice_periodo]).values,"\n")
    print(probabilidades_observadas[indice_periodo].values)
    print(probabilidad_esp.values)

print(observado_chi)


[23  9 20] 

[[0.21153846 0.07692308 0.15384615]
 [0.11538462 0.01923077 0.03846154]
 [0.11538462 0.07692308 0.19230769]]
[[0.17692308 0.06153846 0.16538462]
 [0.06923077 0.03076923 0.05769231]
 [0.15769231 0.06538462 0.21538462]]
[21  5 25] 

[[0.1372549  0.03921569 0.23529412]
 [0.03921569 0.         0.05882353]
 [0.23529412 0.05882353 0.19607843]]
[[0.17692308 0.06153846 0.16538462]
 [0.06923077 0.03076923 0.05769231]
 [0.15769231 0.06538462 0.21538462]]
[22  8 21] 

[[0.19607843 0.05882353 0.19607843]
 [0.09803922 0.03921569 0.01960784]
 [0.1372549  0.05882353 0.19607843]]
[[0.17692308 0.06153846 0.16538462]
 [0.06923077 0.03076923 0.05769231]
 [0.15769231 0.06538462 0.21538462]]
[23 11 17] 

[[0.23529412 0.09803922 0.11764706]
 [0.07843137 0.03921569 0.09803922]
 [0.1372549  0.07843137 0.11764706]]
[[0.17692308 0.06153846 0.16538462]
 [0.06923077 0.03076923 0.05769231]
 [0.15769231 0.06538462 0.21538462]]
[15  8 28] 

[[0.11764706 0.03921569 0.1372549 ]
 [0.01960784 0.05882353 0.0