In [7]:
import io
import sys, os
import pandas as pd
import numpy as np
import pandas as pd
import itertools 
import matplotlib.pyplot as plt

In [8]:
#SE USAN LAS FUNCIONES EN LA CARPETA MARKOVIANAS PARA TRAER LAS MATRICES DE TRANSICION

#pip install nbformat
class HiddenPrints:
    def __enter__(self):
        self._original_stdout = sys.stdout
        sys.stdout = open(os.devnull, 'w')

    def __exit__(self, exc_type, exc_val, exc_tb):
        sys.stdout.close()
        sys.stdout = self._original_stdout

with HiddenPrints():
    %run -i ../MARKOVIANAS/Ford_Case2.ipynb
    ford_accepted, ford_transition = sendInfoToAnalize()
    %run -i ../MARKOVIANAS/Honda_Case2.ipynb
    honda_accepted, honda_transition = sendInfoToAnalize()
    %run -i ../MARKOVIANAS/NIO_Case2.ipynb
    NIO_accepted, NIO_transition = sendInfoToAnalize()
    %run -i ../MARKOVIANAS/Toyota_Case2.ipynb
    toyota_accepted, toyota_transition = sendInfoToAnalize()

states_map = {"B1":0, "B2":1, "B3":2, "S1":3, "S2":4, "S3": 5} 
company_map= {"Ford": ford_transition, "Honda": honda_transition, "NIO": NIO_transition, "Toyota": toyota_transition}


In [10]:
#PROBABILIDAD DE QUE SUBA 3 DÍAS SEGUIDOS
for company in company_map:
    for 

[[0.37101449 0.10434783 0.01449275 0.36231884 0.11304348 0.03478261]
 [0.28431373 0.11764706 0.06862745 0.33333333 0.12745098 0.06862745]
 [0.5        0.09090909 0.04545455 0.09090909 0.27272727 0.        ]
 [0.34985423 0.10787172 0.02040816 0.37609329 0.11953353 0.02623907]
 [0.38053097 0.08849558 0.01769912 0.36283186 0.08849558 0.0619469 ]
 [0.34210526 0.13157895 0.         0.34210526 0.10526316 0.07894737]]
[[0.33876221 0.10423453 0.0228013  0.3713355  0.11400651 0.04885993]
 [0.23529412 0.19327731 0.04201681 0.39495798 0.12605042 0.00840336]
 [0.28       0.08       0.04       0.32       0.2        0.08      ]
 [0.31944444 0.125      0.02222222 0.36111111 0.15277778 0.01944444]
 [0.35245902 0.10655738 0.03278689 0.39344262 0.08196721 0.03278689]
 [0.33333333 0.1        0.         0.46666667 0.06666667 0.03333333]]
[[0.38461538 0.13105413 0.01709402 0.32763533 0.10826211 0.03133903]
 [0.2601626  0.16260163 0.01626016 0.43089431 0.08943089 0.04065041]
 [0.35       0.1        0.      